---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    plex_domain: plex.theblueroost.me

bastion:
  hosts:
    bastion_vps:
      ansible_host: 178.156.216.177

homeserver:
  hosts:
    home_docker:
      ansible_connection: local
