---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    plex_domain: watch.theblueroost.me

bastion:
  hosts:
    bastion_vps:
      ansible_host: 37.27.205.154

homeserver:
  hosts:
    home_docker:
      ansible_connection: local
